<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice {{ $billing->invoice_number }}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: Segoe UI, system-ui, sans-serif; color: #0f172a; padding: 40px; max-width: 800px; margin: 0 auto; }
        h1 { font-size: 1.5rem; color: #0d9488; margin-bottom: 4px; }
        .meta { color: #64748b; font-size: 0.875rem; margin-bottom: 32px; }
        table { width: 100%; border-collapse: collapse; margin: 24px 0; }
        th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }
        th { background: #f8fafc; font-size: 0.8125rem; text-transform: uppercase; color: #64748b; }
        .amount { text-align: right; }
        .totals { margin-top: 24px; text-align: right; }
        .totals p { margin: 6px 0; font-size: 0.9375rem; }
        .totals .grand { font-size: 1.25rem; font-weight: 700; color: #0d9488; }
        .totals .due { color: #b91c1c; font-weight: 600; }
        .footer { margin-top: 48px; font-size: 0.8125rem; color: #94a3b8; }
        @media print { body { padding: 20px; } .no-print { display: none; } }
    </style>
</head>
<body>
    <button class="no-print" onclick="window.print()" style="margin-bottom:20px;padding:8px 16px;cursor:pointer;">Print / Save as PDF</button>

    <h1>{{ $clinicName }}</h1>
    <p class="meta">Invoice <strong>{{ $billing->invoice_number }}</strong> &middot; {{ $billing->billed_at->format('M d, Y') }}</p>

    <table>
        <tr><th>Patient</th><td>{{ $billing->patient->name }} ({{ $billing->patient->patient_code }})</td></tr>
        @if($appointment)
        <tr><th>Doctor</th><td>{{ $appointment->doctor->user->name ?? '—' }} — {{ $appointment->doctor->department->name ?? '—' }}</td></tr>
        <tr><th>Visit date</th><td>{{ $appointment->appointment_date->format('M d, Y h:i A') }}</td></tr>
        @endif
        <tr><th>Payment status</th><td>{{ ucfirst($billing->status) }}</td></tr>
    </table>

    <table>
        <thead>
            <tr><th>Description</th><th class="amount">Amount</th></tr>
        </thead>
        <tbody>
            @if($billing->previous_due > 0)
            <tr>
                <td>Previous balance due</td>
                <td class="amount">${{ number_format($billing->previous_due, 2) }}</td>
            </tr>
            @endif
            <tr>
                <td>Doctor charge (this visit)</td>
                <td class="amount">${{ number_format($billing->charge_amount, 2) }}</td>
            </tr>
            <tr>
                <td><strong>Total payable</strong></td>
                <td class="amount"><strong>${{ number_format($billing->total_amount, 2) }}</strong></td>
            </tr>
            <tr>
                <td>Amount paid</td>
                <td class="amount">− ${{ number_format($billing->paid_amount, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="totals">
        <p>Previous due: ${{ number_format($billing->previous_due, 2) }}</p>
        <p>Doctor charge: ${{ number_format($billing->charge_amount, 2) }}</p>
        <p class="grand">Total: ${{ number_format($billing->total_amount, 2) }}</p>
        <p>Paid: ${{ number_format($billing->paid_amount, 2) }}</p>
        <p class="due">Balance due: ${{ number_format($billing->due_amount, 2) }}</p>
    </div>

    @if($billing->notes)
    <p style="margin-top:24px;font-size:0.875rem;"><strong>Notes:</strong> {{ $billing->notes }}</p>
    @endif

    <p class="footer">Generated by MedEasy &middot; {{ now()->format('M d, Y') }}</p>
</body>
</html>
